### ISSUE TITLE
How to get result from two different subscription ?

### ISSUE THREAD

**Issue by GithubRanjithS** [helderpinto/AzureOptimizationEngine#134] opened 2024-07-09 07:00 UTC
All Although I could see two separate files for each subscription in storage, I was unable to access the result in Runbook from another subscription.

**Comment by helderpinto** [comment] 2024-07-09 07:46
Hi, @GithubRanjithS. Thanks for reporting this issue. Can you explain better what you mean by being "_unable to access the result in Runbook from another subscription_"? Didn't you mean "Workbook" instead of "Runbook"? Which specific runbook/workbook are you referring to? If you see two separate files per subscription, then they should be both ingested into Log Analytics after some time and its data should become available in any workbook that depends on that data.

**Comment by GithubRanjithS** [comment] 2024-07-09 07:50
Hi, Resources Inventory workbook, display 2 subscriptions
But in Recommendations workbook show only 1 subscription.

**Comment by GithubRanjithS** [comment] 2024-07-09 07:55
when I run this following query in Log Analytics.  I can be able to see both subscription

AzureOptimizationResourceContainersV1_CL
| where TimeGenerated > ago(1d)
| where ContainerType_s == 'microsoft.resources/subscriptions'
| project SubscriptionGuid_g, ContainerName_s

Not sure why it's not displaying in recommendation workbook

**Comment by helderpinto** [comment] 2024-07-09 08:07
@GithubRanjithS, if you see those subscriptions in other reports, then their absence from the Recommendations workbook might simply be because there are no recent recommendations for those subscriptions. Can you check whether the JSON blobs that landed into the "recommendations" Storage container include any recommendation for the missing subscriptions?

**Comment by GithubRanjithS** [comment] 2024-07-09 08:31
@helderpinto Yes, I can be able to see the JSON file that contain missing subscription details and its recommendation.

**Comment by helderpinto** [comment] 2024-07-09 10:01
Was the JSON file generated in the last 7 days?

**Comment by GithubRanjithS** [comment] 2024-07-09 10:12
@helderpinto file generated on yesterday

**Comment by helderpinto** [comment] 2024-07-09 11:21
Can you please run the query below on the LA workspace?

```
AzureOptimizationRecommendationsV1_CL
| where TimeGenerated > ago(7d)
| distinct SubscriptionGuid_g, SubscriptionName_s
```

Which subscriptions does the query return?

**Comment by GithubRanjithS** [comment] 2024-07-09 11:29
when i run this query showing one subscription, another one is missing

**Comment by helderpinto** [comment] 2024-07-09 11:34
Can you manually start the `Ingest-RecommendationsToLogAnalytics` Automation runbook and re-run the query above after 10-15 minutes, to check whether there is any missing ingestion processing?

**Comment by GithubRanjithS** [comment] 2024-07-09 11:46
manually start the Ingest-RecommendationsToLogAnalytics
Log shows Found 0 new blobs to process...
also query display same one subscription

**Comment by helderpinto** [comment] 2024-07-09 12:08
Can you paste here an excerpt of the recommendations JSON content that includes the missing subscription?

**Comment by GithubRanjithS** [comment] 2024-07-09 12:40
@helderpinto, Json from recommendationsexports?

**Comment by GithubRanjithS** [comment] 2024-07-09 12:43
Sorry, i this JSON have details about only one subscription,
The export csv file is having both subscription details.

**Comment by GithubRanjithS** [comment] 2024-07-09 12:53
Missing subscription one of the recommendation is
Enable auto scale on your Azure Cosmos DB database or container

**Comment by helderpinto** [comment] 2024-07-09 13:06
I want you to share the JSON file from the `recommendationsexports` container. This is where recommendations in Log Analytics come from.

**Comment by GithubRanjithS** [comment] 2024-07-09 13:32
the JSON have some confidential details like subscription etc.., here i attached screen short of the container

![Capture](https://github.com/helderpinto/AzureOptimizationEngine/assets/88855503/11867caf-5015-4161-a41f-a07ca78892e0)

**Comment by helderpinto** [comment] 2024-07-09 13:56
Can you please [DM me](https://www.linkedin.com/in/hspinto/) with the content of that JSON you highlighted?

**Comment by GithubRanjithS** [comment] 2024-07-09 14:24
Am not a premium user i send you the connection request
, can i ask your email?

**Comment by helderpinto** [comment] 2024-07-10 16:16
Hi, @GithubRanjithS. The files you sent me contain recommendations coming only from a single subscription (ID starting with `546d`). Therefore, it's an expected behavior of the Recommendations workbook to show only recommendations for that subscription.

Now, for the runbooks you reported to be failing, please ensure you grant the required permissions to the AOE Automation Account's managed identity. For the `Export-ReservationsUsageToBlobStorage`, `Export-PriceSheetToBlobStorage`, and `Export-SavingsPlansUsageToBlobStorage` runbooks, [see instructions here](https://github.com/helderpinto/AzureOptimizationEngine?tab=readme-ov-file#enabling-the-reservations-and-benefits-usage-workbooks). For the `Export-RBACAssignmentsToBlobStorage`, ensure you grant the Global Reader role to the AOE Managed Identity in your Entra ID tenant (this is only required if you want to use the Identities and Roles workbook - it is not required for Cost optimizations).

**Comment by GithubRanjithS** [comment] 2024-07-11 13:32
I sent you new JSON this contains few subscriptions. 

after I have executed Ingest-RecommendationsToSQLServer, Recommendation still shows only two subscriptions

**Comment by helderpinto** [comment] 2024-07-11 14:12
@GithubRanjithS , if you want to see recommendations in Azure workbook, you need to run `Ingest-RecommendationsToLogAnalytics' instead.

I understand that are you running AOE manually, maybe to speed things up. However, AOE was designed to generate new recommendations once per week and it does not depend on users executing runbooks manually. Trying to anticipate its schedules may lead to unexpected behavior or temporary inconsistencies.

**Comment by GithubRanjithS** [comment] 2024-07-11 16:16
Thank you! working now 👍

**Closed** 2024-07-17 20:12 UTC
